### ISSUE TITLE
Use OpenType Features to make under-text always work

### ISSUE THREAD

**Issue by davelab6** [graphicore/librebarcode#11]
A user reported offline,

> If the "Libre barcode 128 text" font is used with only numbers, the text below the barcode is incorrect. Here are the reproducible use cases:
>
>* Encoding with [bcgen site](http://bcgen.com/fontencoder) 
>
>Sample text "123456789" and "123 456 789" both display incorrect text below the barcode but scan correctly.
>
> ![bcgenencoding](https://user-images.githubusercontent.com/261579/32850159-61a37456-c9ff-11e7-9410-c4df87c95a54.png)
>
>* Encoding with [jtbarton site](http://jtbarton.com/Barcodes/BarcodeStringBuilderExample.aspx):
>
>Sample text "123456789" displays incorrect text below barcode but scans correctly. (Sample text "123 456 789" works as expected)
>
> ![jtbartonencoding](https://user-images.githubusercontent.com/261579/32850143-55f1e98a-c9ff-11e7-8bf8-a011e2b85f7b.png)

@graphicore explained,

> What's happening is, that the Barcode 128 format has [a mechanism for optimizing its length](https://en.wikipedia.org/wiki/Code_128#Barcode_length_optimization)
>
> i.e. a number like 123 can be optimized to use only two symbols [Switch to Code C] and [Symbol #91], which represents 123 in `Code C`. If the tool to encode the barcode decides that it is saving symbols using another "sub-encoding" than Code B (the default), this is what happens.  
>
> I also explained, that I'm not sure if or how well this can be done with OT-Features and I think we decided to go with simple none-fancy OT-Features in the first round. One thing I find especially complicated is that we sometimes need to show 3 glyphs below one Symbol, which needs a lot of space and ends the monospaced relation between the text below and the symbols.
>
> There are also many symbols without any text below in Code 128 B, especially the ones that are switching between codes and also some others, that don't have proper glyph representations in Code B ([DEL] [FNC3] ...). This is why we see so much empty space in the screen shots. Maybe a set of debug-fonts or a debug stylistic-set OT-Feature could help, by showing what is going on in the fonts/barcodes - like in a [Unicode fallback font](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=UnicodeBMPFallbackFont)

- [ ] investigate if OTF is reasonably feasible
- [ ] if yes, make a "barcode decoded" font; and
- [ ] implement the OT features

**Comment by khaledhosny** [comment]
Are there any examples of barcodes (with text) using double-encoded digits?

**Comment by graphicore** [comment]
I think usually this would not be done within the font. Instead, one would write the barcode and then centered below write the encoded value.

**Comment by davelab6** [comment]
Doubling of text in 2 fonts like that is a hack, which I think OpenType features can obsolete, no? :)

**Comment by davelab6** [comment]
I'll request examples from the customer

**Comment by khaledhosny** [comment]
I’m interested to see how the digits are positioned related to the bars.

**Comment by khaledhosny** [comment]
Here is how the texts above show now (in order):
![a](https://user-images.githubusercontent.com/93914/34104141-f858f076-e3f7-11e7-8c43-6377cab09ebc.png)
![b](https://user-images.githubusercontent.com/93914/34104145-fb610f10-e3f7-11e7-99c6-c49951a2328b.png)
![c](https://user-images.githubusercontent.com/93914/34104146-fe06f50e-e3f7-11e7-8335-003bc29034d6.png)
![d](https://user-images.githubusercontent.com/93914/34104150-0114c104-e3f8-11e7-949f-0c684be56e4b.png)
