### ISSUE TITLE
Switching to Python?

### ISSUE THREAD

**Issue by khaledhosny** [graphicore/librebarcode#13]
Are there any strong reasons for using JS and node to draw the glyphs (while using Python to build the fonts)? I find the current setup needlessly to complex and IMHO it would be simpler if the glyphs were drawn using Python as well.

My `node_modules` is 94 MB, and `venv` is another 82 MB. ~200 MB of dependencies to build the fonts is a bit too much IMHO.

**Comment by graphicore** [comment]
> Are there any strong reasons for using JS

There is a distant plan/possibility to make this a single page web app, that can generate UFOs on the fly.

I'm guessing you are not really fond of JavaScript, though. It's rather uncommon in the type world, I get this.

> I find the current setup needlessly to complex … it would be simpler if the glyphs were drawn using Python as well.

I disagree. IMHO It's almost the same effort in either language.

**Comment by davelab6** [comment]
How many Gb on your computer, Khaled???

**Comment by khaledhosny** [comment]
It is not about disk space, but downloading the dependencies which took me several minutes. But never mind, it was just a thought.
