### ISSUE TITLE
Document Use of code128 Generation in Libre Barcode 128

### ISSUE THREAD

**Issue by xd1936** [graphicore/librebarcode#14]
This is a great project, keep up the good work!

If I was to use the Libre Barcode 128 font in my web project, there is no documentation anywhere as to how to generate a code128 checksum, convert a string to code128, or what the start/stop characters are in your font. Please consider adding some documentation to this project's `README`, because simply applying your font to a span of text will not render a scannable barcode. Thanks!

**Comment by homerggg** [comment]
For your information, I found out that the following are the start and stop characters : Ì and Î.

**Comment by graphicore** [comment]
Sorry for responding slowly.

@xd1936 for code 128 you'll need a generator, because the encoding of that is not one to one what you type. 

This one usually works for me: http://www.jtbarton.com/Barcodes/BarcodeStringBuilderExample.aspx
 (but there are others as well) the result of `0123456` is `Í!7MÈ6lÎ`

![selection_200](https://user-images.githubusercontent.com/393132/35995053-8f832e60-0d12-11e8-83a4-db8507ec9e68.png)

from here: https://fonts.google.com/specimen/Libre+Barcode+128+Text

**Comment by xd1936** [comment]
Understood! How would I find more information on the algorithm that converts a string to properly encoded text? I'm looking to implement this in Javascript in a project.

**Comment by robertjpayne** [comment]
@graphicore yea it'd be super useful to have an open source implementation of an encoder that works for this font.

There's zero documentation anywhere about it and your links no longer work.

**Comment by graphicore** [comment]
Agreed. There's documentation at Wikipededia: https://en.wikipedia.org/wiki/Code_128 (see [Barcode length optimization](https://en.wikipedia.org/wiki/Code_128#Barcode_length_optimization) What we need is a good dynamic algorithm to find the shortest encoding.

Here's a working online encoder: https://www.bcgen.com/fontencoder/

**Comment by RiverHeart** [comment]
Still trying to understand Code128 myself but I have what I think is a working, rudimentary Powershell implementation [here](https://github.com/RiverHeart/Powershell-Barcodes). No digit optimization yet, but if I understand correctly, it just encodes double digits as a single value with Code C, so you'd need a lookahead to detect double digits. Shouldn't be difficult to convert to Python/Javascript if anyone wants to.

**Comment by graphicore** [comment]
here: https://graphicore.github.io/librebarcode

**Comment by RichardSchwinn** [comment]
This is all terrific.  How can I access the encoder in my php / java apps?
