### ISSUE TITLE
Windows 10: Microsoft Word: Barcode Glyphs display as arial characters 

### ISSUE THREAD

**Issue by Spereicle** [graphicore/librebarcode#18]
I'm having a problem were the barcode glyphs display as arial characters in word. 
i.e. instead of a barcode, letters are displayed both on the screen and when printed. 

Libre Fonts are working as expected in excel -- the barcode glyph is displaying in the cell and human readable characters are displaying in the formula bar.

Is there a way of making these display & print properly in word?

Font: All Libre Barcode fonts

WinVer: 10.0.17763.557
Word & Excel: Office 2016 (16.0.11727.20244)

Other anomalies:
Displays properly as barcode Glyphs in Notepad
Displays as human readable Arial characters in WordPad.

**Comment by graphicore** [comment]
Hi, thanks for reporting!

I'm afraid I personally don't have access to a windows machine, not to speak of these versions of Word and Excel. Hence, it is basically impossible for me to do debugging in this case.

@m4rc1e sorry for bothering you, but do you have a clue of what this could be?

I could just try to build a new version with a current fontmake, hoping it was somehow a problem there that got fixed in the mean time.

**Comment by Spereicle** [comment]
Thanks @graphicore, I'm just beginning with this, so troubleshooting is very hit and miss. Currently using FontForge to recompile it and test.

Any additional insights much appreciated.

**Comment by m4rc1e** [comment]
The fonts lack dsig tables. I remember that MS Office doesn't like fonts which lack this table (~2015). 

I've attached a barcode font which has a dummy dsig table. Please try it out and let us know if it works.

[LibreBarcode39-Regular.ttf.zip](https://github.com/graphicore/librebarcode/files/3405369/LibreBarcode39-Regular.ttf.zip)

**Comment by graphicore** [comment]
@m4rc1e 

Interesting! Because it seems iit has been thought of:

https://github.com/graphicore/librebarcode/blob/825314e5223752b1e4be2d6d906af935fe6040c1/app/bin/buildAll#L239

**Comment by m4rc1e** [comment]
I only inspected the downloadable fonts from Google Fonts. They may have post processed them.

**Comment by graphicore** [comment]
@Spereicle where did you get your fonts from?

Maybe we should also look at font versions ...

I just ran Font Bakery [report](https://fontbakery.graphicore.de/report/a4483ef3-2a61-4c33-acfb-b2afbf1255c9) with the files from the [latest release](https://github.com/graphicore/librebarcode/releases/tag/v1.003-alpha) and the DSIG check passes.There are some other fails though, maybe some of those are responsible (name table, OS/2 tabe)

**Comment by Spereicle** [comment]
Thank you both @m4rc1e and @graphicore,

I downloaded the fonts from the Google font repo. 
The one I am focusing on is: LibreBarcode39Text-Regular.ttf (but I did install and check all libre barcode fonts)
The font version is: 1.002; ttfautohint (v1.6).

The font provided by @m4rc1e operates the same (works in excel, does not in word.)

**Comment by graphicore** [comment]
I had a follow up from @Spereicle via email, who solved his problem but didn't post his ttf in because:

> The only reason I sent it to you vs the tracker is that I have little font skill and did not want my bastardized version of your font creating a versioning issue. While I did get it to work, I have little certainty that the ttf file I attached uses best practices, is properly attributed / copywritten, etc.
>
> Thus I would be hesitant to include the ttf file I attached in a public forum as it may reflect negatively on your good work if someone erroneously attributes my lack of knowledge to you.

He also allowed me to publish the contents of that email.

Thanks @Spereicle for your thoughtfulness and for helping with this issue! However, to have this case documented to have and a place to pick it up again, I prefer having your file attached to this thread.

Here's the email from @Spereicle 07/19/2019 09:48:56 AM:

> Hello Lasse,
>
>Thank you for your work and assistance!
> 
>Attached is a LibreBarcode39Text-Regular.ttf derived font file which works in MS Word. The font is for my personal internal use and, as my font knowledge is limited, it is being sent directly to you vs. potentially polluting your git repo by being posted in the ‘issues’ thread. If it is in anyway beneficial to you, then I’m glad.
> 
> I created it in FontForge by:
> * merging the glyphs from LibreBarcode39Text-Regular.ttf into an existing font template
> * updating the em, ascent, and decent values
> * updating the ‘PS Names’ fields
> * updating the ‘OS/2’ values
> * updating the ‘TTF Names’ values
> * removing the “space” glyph as it was causing an anomaly.
> 
> Also attached is a test file created in word, showing the attached font and another publicly available 3 of 9 font.

[Attachments on drive.google.com](https://drive.google.com/open?id=15szQ7itB9KV5ltuMCEouVNBTFXJ5hLq4)

**Comment by Rudu-be** [comment]
I am havening the same problem with the code 128 font.

I do not know how the change it myself ,can someone make a fix for this one?

**Comment by graphicore** [comment]
I believe this works now, it does at least on my version of Word. See #34 

Google Fonts is not yet updated but underway. You can download the fonts from the pre-release: https://github.com/graphicore/librebarcode/releases/tag/pre-v1.008

![Screenshot from 2020-12-15 17-21-14_cropped](https://user-images.githubusercontent.com/393132/102299975-44435c00-3f54-11eb-803d-b1afa6f375ec.png)

Before:

![Screenshot from 2020-12-15 17-22-03](https://user-images.githubusercontent.com/393132/102299762-d0a14f00-3f53-11eb-9d9f-67602664e010.png)

After:

![Screenshot from 2020-12-15 18-27-08](https://user-images.githubusercontent.com/393132/102299796-e151c500-3f53-11eb-93e6-29b89e50d1bd.png)
