### ISSUE TITLE
EAN 13 not working in Windows' MS Word 2013 

### ISSUE THREAD

**Issue by davelab6** [graphicore/librebarcode#28]
Feedback on EAN 13

> I downloaded the font to my Mac. Install the font on the Mac. I run the TextEdit software. I am writing 1234567891234 in the application. I select the text, I choose the font, I see a barcode displayed.
> 
> ![image2](https://user-images.githubusercontent.com/261579/96263399-f2507b00-0f90-11eb-956e-b200b823934d.png)
> 
> I download the font to a PC with Windows, and install the font. I run Word 2013, I write 1234567891234. I select the font, I change the font, the writing changes but I do not see a Barcode appear.
> 
> ![image1](https://user-images.githubusercontent.com/261579/96263402-f2507b00-0f90-11eb-8c9e-58ceab0b35d0.png)
>
> Tried again with what I believe is a correctly checksummed number:
> 
> <img width="660" alt="Screen Shot 2020-10-16 at 9 21 00 AM" src="https://user-images.githubusercontent.com/261579/96263437-fe3c3d00-0f90-11eb-9294-eb873dace7ee.png">
>

**Comment by graphicore** [comment]
Ok, the lookups are all in `calt`, I wonder if which cases Word doesn't activate features. The font has a dummy DSIG.

**Comment by graphicore** [comment]
Ok, I'm right now investigating this. I only have access to the current Word 365 (2019, Version 16...)desktop app right now.

![Screenshot from 2020-10-19 18-12-30](https://user-images.githubusercontent.com/393132/96477472-d5d56c80-1236-11eb-8ee2-8c91750bba03.png)


There, I can activate "contextual alternates" (that's the calt feature) optionally, I found that deeply buried under:

 * Apply Styles
 * Modify …
 * Format …
 * Font …
 * Advanced
 * [x] Use Contextual Alternates


![Screenshot from 2020-10-19 18-17-35](https://user-images.githubusercontent.com/393132/96477978-6b70fc00-1237-11eb-9516-2f207e7b03df.png)

Given that in https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-calt we have:

> *UI suggestion*: This feature should be active by default.

I think that is rather disappointing. @davelab6 any suggestions for a better suitable feature tag here? I can also just search one that is on by default and working.
Also, Installing Word 2013 is not straight forward any more, I'd put some more time into this if necessary, but first try the other feature approach.

**Comment by khaledhosny** [comment]
Try `ccmp`, if this does not work then Word does not activate any features (for so-called simple text) by default.

**Comment by davelab6** [comment]
`liga` is usually the most widely implemented feature, I think

**Comment by khaledhosny** [comment]
If `ccmp` is not implemented/enabled by default then it is a seriously broken implementation to worry about it. `liga` can be optionally disabled (by the user or automatically when there is tracking), which is not something desired here.

**Comment by graphicore** [comment]
* `ccmp`: seems to get enabled together with that "Use Contextual Alternates" checkbox. I.e. there's no difference to using `calt`.
* `liga`: must be enabled explicitly under "Ligatures" by selecting "Standard Only" or "Standard and Contextual" or "All"
* `kern`: I tried this, must be activated as well, together with a minimal point size. Did only work together with "Use Contextual Alternates" on though. To be clear, both was needed: "Kerning for fonts" with matched point size **and** "Use Contextual Alternates" 
* `ss01` worked as expected when turned on in "Stylistic sets: 1". **However** it also worked with "Use Contextual Alternates" selected but "Stylistic sets" turned off (= "Default"). I was also able to enable my `ss01` selecting e.g. "Stylistic sets: 4" etc. Bonkers.
* `locl` same as `ccmp`. At this point, it seems to me that "Use Contextual Alternates" just activates generic GSUB lookups/features, although, I also have one GPOS rule (for the leading number) in the feature that also is activated each time.
* `ltra` did not work by default, did work with "Use Contextual Alternates"



Testing had to be done like this:
* install the font in Windows
* restart the VirtualBox machine
* test in Word

As it seems that the font is cached somewhere and the cache is not invalidated when a new version of the font is installed. I tried restarting only Word, didn't work for me.

**Comment by khaledhosny** [comment]
This proves my suspicion that Word does not enable OpenType layout for so-called simple text, and probably nothing in the font is going to convince it otherwise.

> As it seems that the font is cached somewhere and the cache is not invalidated when a new version of the font is installed. I tried restarting only Word, didn't work for me.

You might need to remove the old font first, Windows seems to get bonkers when installing a new version of the same font.

**Comment by thlinard** [comment]
OpenType features (a selected few) first appeared in Word 2010 for Windows and Word 2011 for Mac (the UI has not changed since). None are activated by default.

**Comment by khaledhosny** [comment]
> None are activated by default.

For Latin and probably other scripts it deems ”simple”, Arabic, for example, always had default features enabled by default.

**Comment by graphicore** [comment]
> For Latin and probably other scripts it deems ”simple”. Arabic, for example, always had default features enabled by default.

And how does it chose the script? Unicode or manual user input? Maybe we can trigger it somehow, e.g. with a special character.

MS Excel seems even worse.

**Comment by thlinard** [comment]
> > None are activated by default.
> 
> For Latin and probably other scripts it deems ”simple”. Arabic, for example, always had default features enabled by default.

Yes, of course. For the so-called "complex" scripts, the support is much older. But there is still no UI for them—it's enabled by default and that's it.

**Comment by graphicore** [comment]
@davelab6 not sure what to make out of this now:

 * nothing wrong with the font, instead MS doesn't follow their own recommendations in the OT standard
 * there's a way to activate the `calt` etc. feature in Word, just with a somewhat deeply buried UI
 * I didn't find another way to activate these OpenType features yet
 * I'm not sure if there's a better way to implement EAN 13, but it could be done (worse/less elegantly) without OpenType features, by using a direct char codes to pattern symbol mapping e.g. for 0-9 from SetA enter A-J; from setB enter a-j etc. But that way we'd need an encoder, because the knowledge how to encode would not be in the font and the actual input string would be just gibberish. The font would be harder to use but arguably better portable to bad text shapers.

**Comment by graphicore** [comment]
Thanks @khaledhosny and @thlinard for the insightful input!

**Comment by thlinard** [comment]
> > For Latin and probably other scripts it deems ”simple”. Arabic, for example, always had default features enabled by default.
> 
> And how does it chose the script? Unicode or manual user input? Maybe we can trigger it somehow, e.g. with a special character.

Well, I imagine that it would be possible to use a rather dirty hack: that the calt function pretends to be a function for the Arabic script (not the "Default" script). It could succeed in fooling Word…

**Comment by thlinard** [comment]
> Ok, the lookups are all in `calt`, I wonder if which cases Word doesn't activate features. The font has a dummy DSIG.

I should have started there: only "Libre Barcode 128 Text" has a `calt` feature  (it's even the only one to have a GSUB table), so, as it's not clear from the screenshot, maybe the user confused Libre Barcode 128 Text with Libre Barcode 39 Text in the Windows test?

**Comment by graphicore** [comment]
@thlinard see #27 this is about adding a new barcode standard.

**Comment by thlinard** [comment]
Oh, indeed! Sorry!

**Comment by davelab6** [comment]
> nothing wrong with the font, instead MS doesn't follow their own recommendations in the OT standard

Ha! Then, this issue can be closed, but we should note that in the README, so leaving open to resolve with such a commit

**Comment by davelab6** [comment]
Lasse suggested

> I’d make a character style, like this: https://support.microsoft.com/en-us/office/customize-or-create-new-styles-d38d6e47-f6fc-48eb-a607-1eb120dec563#new

And I suggested to do the ascii style version he mentioned above

**Comment by graphicore** [comment]
ascii input method ("compatible") is available with #30 
Also a full featured unicode input method ("fallback").

Docs and encoder tools are WIP. The "compatible" encoder will be rather simple js and produce output aligned with: https://grandzebu.net/informatique/codbar-en/ean13.htm

The "fallback" encoder is based on harfbuzzjs (with webasm) and uses the result of shaping to get the unicodes for each glyph.

**Comment by graphicore** [comment]
Access to the encoders: https://graphicore.github.io/librebarcode/documentation/ean13.html#ean13-encoder

Screenshot of a working character style setup:
 
![Screenshot from 2020-12-15 18-02-11](https://user-images.githubusercontent.com/393132/102300499-58d42400-3f55-11eb-8ab1-c7a1ebb0fcf7.png)

**Comment by nasusonetrick** [comment]
im using the fint in Visual Studio 2019 to read Text from barCode scanner and turn it into barcode that can be printed , 
and im facing an issue, the last digit sometimes show this way   ">"   ???
the codebars im scanning are UAN13 , the codebar scanner does not print any weird characters only digits , something like 1234567890123
