### ISSUE TITLE
Name Table fontbakery issue.

### ISSUE THREAD

**Issue by graphicore** [graphicore/librebarcode#4]
Somewhere the names make fontbakery unhappy.

We have:  `Libre Barcode 128 Text Regular` but fb wants  `Libre Barcode128 Text`.

* the `Regular` should not be there. I'll remove it.
* the space between `Barcode` and `128`, I believe it should be there, but FB dislikes the numbers without space before.
* `TYPOGRAPHIC_FAMILY_NAME` I'll try to remove it.

Two examples:

### Assure valid format for the main entries in the name table.
* ERROR: [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Libre Barcode128 Text' but got 'Libre Barcode 128 Text Regular'
* ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Libre Barcode128 Text Regular' but got 'Libre Barcode 128 Text Regular'
* Warning: Font is not expected to have a [TYPOGRAPHIC_FAMILY_NAME(16):WINDOWS(3)] entry!

---

### Assure valid format for the main entries in the name table.
* ERROR: [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Libre Barcode39' but got 'Libre Barcode 39 Regular'
* ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Libre Barcode39 Regular' but got 'Libre Barcode 39 Regular'
* Warning: Font is not expected to have a [TYPOGRAPHIC_FAMILY_NAME(16):WINDOWS(3)] entry!

**Comment by graphicore** [comment]
OK, got this down to:


### Assure valid format for the main entries in the name table.
* ERROR: [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Libre Barcode128 Text' but got 'Libre Barcode 128 Text'
* ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Libre Barcode128 Text Regular' but got 'Libre Barcode 128 Text'

I assume the rest is commonly done with whitelisting in fontbakery, like it happened with `'VT323': 'VT323'` or `'PressStart2P': 'Press Start 2P'`

**Comment by davelab6** [comment]
Exactly

**Comment by davelab6** [comment]
Also the copyright notice inside the fonts should be

    "Copyright 2017 The Libre Barcode Project Authors (lasse@graphicore.de)

**Comment by graphicore** [comment]
Here you go:

https://github.com/graphicore/librebarcode/releases/tag/v1.001-alpha
