### ISSUE TITLE
Unable to scan Barcodes made by inDesign and "Libre Barcode 39" or "Libre Barcode 128"

### ISSUE THREAD

**Issue by KiNdGi4nT** [graphicore/librebarcode#53]
Hello,

i was looking for a way to fast generate barcodes in inDesign of various codes. 

So, i installed the Libre Barcode font family and then opened inDeisgn and wrote in a text field the digits/codes i would like to "transform" into a barcode. It seems working in iD as the numbers i enter are displayed as barcode lines. After making a pdf of the sheet and printing is, the scanner dosent recognize the barcodes and dosent scan them. I printed this page (https://graphicore.github.io/librebarcode/documentation/code128.html) and i was able to scan the 2 barcodes on it with the scanner. So it actually should work. But when i "write a barcode in inDeisgn" and print the Sheet i am not able to scan the barcode.

are there any known issues with inDesign and the Libre Font family? Do you have a solution for this issue?

Thank you and regards

PS: i installed the latest Version of the Font family [Version 1.008, Version 1.005]

Used scanner: Honeywell MS9520

**Comment by graphicore** [comment]
Hi. Libre Barcode 39 and Libre Barcode 128 should work in InDesign AFAIK, as the OpenType Features in these fonts are pretty basic. (The EAN-13 font is another beast).

Could you attach pictures/screenshots of the barcodes that don't work as well as the according input strings you used? You can drag and drop the pictures right into the comment box.

Did you read the documentation and encode the input texts accordingly?

**Comment by KiNdGi4nT** [comment]
Hey,

thanks for the fast respond!

Attached you would find a screenshot of the digits (121000288) and the Barcode (in 2 sizes)

I did but i thought this is not related to inDesign :-) I thought i have only to install the font family and then type my digits in inDesign and thats it? I am not a programmer, so i thought the your font family is a easy way to create some barcodes of some digits i have?

Thank you for your help!

Regard
![test](https://user-images.githubusercontent.com/108874465/177770644-69862c13-a39f-459a-a9cb-83ed9fd9776e.PNG)
s

**Comment by graphicore** [comment]
I'm sorry it's not that simple. The documentation applies to everywhere the fonts are used.

For Code 39 you should enter `*121000288*` (Just add `*` asterisks  around the input)

For Code 128, you'd use an encode like the one [in the documentation](https://graphicore.github.io/librebarcode/documentation/code128.html) which produces `Ì1Ç5 "xÄÎ`

These fonts are made to work similarly as prior existing fonts, so they are not that fancy, and if they were that fancy, they would probably not work in InDesign (yet, as InDesign is not very good yet with OpenType Features).

**Comment by graphicore** [comment]
Great! No problem.
