### ISSUE TITLE
Can't use it on php (trying to show a barcode in html using this font)

### ISSUE THREAD

**Issue by maorflex** [graphicore/librebarcode#56]
Hey, I tried to link to the google font in the head of html, using with the needed style, but nothing shows up. What i'm doint wrong?

**Comment by graphicore** [comment]
Hi @maorflex, you don't provide a lot of context about what you are doing. But looking at your edits of the original post it seems like you are using a css class `.ss` to specify the font-family, but your text is not within an element that is selected by that class. Try wrapping your text into an element with that class:

```
<style> .ss { font-family: "Libre Barcode 128 Text"; font-size: 24px; } </style>

<span class="ss">Ìqms3NÎ</span>
```

But, given the lack of context, I can't guarantee that this is the actual/only issue.

**Comment by graphicore** [comment]
Closing for not being responsive.
