### ISSUE TITLE
Wrong variable used

### ISSUE THREAD

**Issue by pfumagalli** [graphicore/librebarcode#64]
https://github.com/graphicore/librebarcode/blob/93bb140146e2a0bec4c56ceddd82d0329553722c/app/lib/ean13Encoder/compatible.mjs#L149-L158

The sliced variable is `addOn5` (line 152), but the referenced variable is `addOn2` (line 158).

**Comment by graphicore** [comment]
Thanks for the report!

**Comment by graphicore** [comment]
This is fixed now.
